-- Ziji V1: extensions, user identity, authentication sessions, and global idempotency records.
-- UUID values are generated by the application; no database UUID generation extension is required.

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE users (
    id uuid PRIMARY KEY,
    email varchar(320) NOT NULL,
    email_normalized varchar(320) NOT NULL,
    email_verified_at timestamptz NOT NULL,
    password_hash varchar(500) NOT NULL,
    password_hash_version smallint NOT NULL CHECK (password_hash_version > 0),
    nickname varchar(100) NOT NULL,
    timezone varchar(64) NOT NULL,
    base_currency char(3) NOT NULL DEFAULT 'CNY'
        CHECK (base_currency IN ('CNY', 'USD', 'HKD', 'JPY', 'EUR')),
    locale varchar(16) NOT NULL DEFAULT 'zh-CN',
    amount_format varchar(32) NOT NULL DEFAULT 'STANDARD',
    status varchar(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'LOCKED', 'CLOSING', 'CLOSED')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    CONSTRAINT uq_users_email_normalized UNIQUE (email_normalized)
);

CREATE INDEX idx_users_status ON users (status);

CREATE TABLE email_challenges (
    id uuid PRIMARY KEY,
    purpose varchar(20) NOT NULL CHECK (purpose IN ('REGISTER', 'RESET_PASSWORD')),
    email_normalized varchar(320) NOT NULL,
    code_hash varchar(500) NOT NULL,
    expires_at timestamptz NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    max_attempts integer NOT NULL CHECK (max_attempts > 0),
    consumed_at timestamptz,
    created_at timestamptz NOT NULL,
    CHECK (expires_at > created_at),
    CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX idx_email_challenge_lookup
    ON email_challenges (email_normalized, purpose, created_at DESC);

CREATE TABLE user_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL,
    device_id varchar(200),
    device_name varchar(200),
    issued_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    revoke_reason varchar(50),
    last_seen_at timestamptz NOT NULL,
    CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CHECK (expires_at > issued_at),
    CHECK (revoked_at IS NULL OR revoked_at >= issued_at),
    CHECK ((revoked_at IS NULL AND revoke_reason IS NULL) OR revoked_at IS NOT NULL)
);

CREATE INDEX idx_sessions_user_active
    ON user_sessions (user_id, expires_at) WHERE revoked_at IS NULL;
CREATE UNIQUE INDEX uq_sessions_user_device_active
    ON user_sessions (user_id, device_id)
    WHERE revoked_at IS NULL AND device_id IS NOT NULL;

CREATE TABLE session_refresh_tokens (
    id uuid PRIMARY KEY,
    session_id uuid NOT NULL,
    token_hash varchar(500) NOT NULL,
    issued_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    revoked_at timestamptz,
    replaced_by_id uuid,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_refresh_tokens_session FOREIGN KEY (session_id) REFERENCES user_sessions (id),
    CONSTRAINT fk_refresh_tokens_replacement FOREIGN KEY (replaced_by_id)
        REFERENCES session_refresh_tokens (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT uq_refresh_tokens_replacement UNIQUE (replaced_by_id),
    CHECK (expires_at > issued_at),
    CHECK (consumed_at IS NULL OR consumed_at >= issued_at),
    CHECK (revoked_at IS NULL OR revoked_at >= issued_at),
    CHECK (replaced_by_id IS NULL OR consumed_at IS NOT NULL)
);

-- An expired token must be consumed or revoked before a new current token is installed for the same session.
CREATE UNIQUE INDEX uq_refresh_tokens_current_session
    ON session_refresh_tokens (session_id)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE TABLE idempotency_records (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL,
    api_major_version smallint NOT NULL DEFAULT 1 CHECK (api_major_version > 0),
    operation_id varchar(100) NOT NULL,
    idempotency_key varchar(100) NOT NULL,
    request_hash char(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    status varchar(16) NOT NULL
        CHECK (status IN ('PROCESSING', 'SUCCEEDED', 'FAILED_RETRYABLE', 'FAILED_FINAL')),
    response_status smallint CHECK (response_status BETWEEN 100 AND 599),
    response_reference jsonb,
    resource_type varchar(50),
    resource_id uuid,
    created_at timestamptz NOT NULL,
    completed_at timestamptz,
    expires_at timestamptz NOT NULL,
    CONSTRAINT fk_idempotency_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_idempotency_scope
        UNIQUE (user_id, api_major_version, operation_id, idempotency_key),
    CHECK (expires_at > created_at),
    CHECK (completed_at IS NULL OR completed_at >= created_at),
    CHECK ((resource_type IS NULL) = (resource_id IS NULL)),
    CHECK ((status = 'PROCESSING' AND completed_at IS NULL)
        OR (status <> 'PROCESSING' AND completed_at IS NOT NULL))
);

CREATE INDEX idx_idempotency_expiry ON idempotency_records (expires_at);
CREATE INDEX idx_idempotency_resource
    ON idempotency_records (resource_type, resource_id)
    WHERE resource_id IS NOT NULL;
